### ISSUE TITLE
Add mutation to subscribe user to newsletter

### ISSUE THREAD

**Issue by patrick91** [pythonitalia/pycon#1090]
We need this for the launch, we are using mailchimp, I can setup api keys when needed :)

**Comment by estyxx** [comment]
What do you mean with this?
In the user model, we have `openToNewsletter` field, but you mean *any user* I think... anyone, also who is not registered? Maybe we have to put in a separate model, with an FK to the user model if the newsletter-user is already registered (the same email) or if he will...? 

If we choose to have a dedicated model for this, (that I think is also easier to manage
unsubscribing) maybe we don't need any more `openToNewsletter` flag in the User model...

**Comment by estyxx** [comment]
Just to recap this: 
We would like to have a component in the Admin to filter and do some query to find a specific target of users to send communications (like reminders and so on...). We would like to use Amazon SES (Simple Email Service) for sending mass emails. But this "tool" doesn't keep a list of subscribers user like Mailchimp does. 

We just have the `openToNewsletter` property in the user model, so we can use that field to filter users willing to receive the newsletter. But we, of course, would like to send the newsletter to unregistered users; in the home page, we have the form where any person can put his email end be able to receive Newsletter without beeing register in the site. 

I think we can create an app where to put a little model for store the list of email addresses (we should also include registered users' mail: in the update Mutation of the user, if  `openToNewsletter` is true we should save the email also in this model/table; if it's false should remove!.  
And we can customize the admin of this app to send direct emails, if we want to send a Newsletter we will select only the users in the Newsletter-Table, otherwise make a query for a specific target...

**Comment by estyxx** [comment]
#1300 I start a draft of this, but now I was working on Submission tag, maybe this weekend I will come back to this... :)
